### get all games
GET http://localhost:5244/games

#### get game by id
GET http://localhost:5244/games/2

### create a game
POST http://localhost:5244/games
Content-Type: application/json

{
    "Genre": "Fighting",
    "Price": 23.67,
    "ReleaseDate": "2019-12-01"
}

### update a game
PUT http://localhost:5244/games/2
Content-Type: application/json

  {
    "name": "WatchDogs Legion",
    "genre": "Free Roam",
    "price": 99.76,
    "releaseDate": "2008-10-26"
  }

### delete a game
DELETE http://localhost:5244/games/4